spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/demo
    # url: jdbc:mysql://mysql-headless.mysql/demo
    username: souress2
    password: 1234
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000 
      max-lifetime: 1800000
  jpa :
    database: mysql
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
server:
  port: 8000
  error.include-message: always

---
spring.profiles: docker
server.port: 8080
spring.datasource.url: jdbc:mysql://mysql-headless.mysql/demo