spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=UTC&characterEncoding=UTF-8
    # url: jdbc:mysql://mysql-headless.mysql/demo
    username: souress2
    password: 1234
    initialization-mode: never # resource 에 있는 schema.sql 을 실행 (기본값: always, 생성안함: never)
    schema: classpath*:db/schema.sql
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000 
      max-lifetime: 1800000
  jpa :
    database: mysql
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.format_sql: true
  main:
    allow-bean-definition-overriding: true # userDetailService 기존 스프링 제공 함수 안쓰고 정의한 함수로 바꾸기 위한 설정

server:
  port: 8081
  error.include-message: always

---
spring.profiles: docker
server.port: 8080
spring.datasource.url: jdbc:mysql://mysql-headless.mysql/demo
